export interface Variable {
    id:number,
    idTipoVariable: number,
    idGrupoVariable: number,
    descripcion: string,
    descripcionResumida: string,
    tip: string,
    codAtributoTecnicoVariedad: number,
    idCliente: number,
    indicadorFotografia: number,
    numFotos: number,
    idInputClasificado: number,
    usaPosible: number,
    variasRespuestas: number,
    rangoMinimo: number,
    rangoMaximo: number,
    manejoRangos: number,
    forzarMinimo: number,
    redondeoMaximo: number,
    cantidadDecimalesMaximo: number,
    redondeoMinimo: number,
    cantidadDecimalesMinimo: number,
    pesoExtra: number,
    varEstratificacion: number,
    tiempoRespuesta: number,
    usoCalculadora: number,
    reqUndVta: number,
    respuestaAfecta: number,
    funcionResult: number,
    numeroOrden: number,
    respuestaObligatoria: number,
    observaciones: string,
    explicacionFuncionamiento: string,
    alias1: string,
    alias2: string,
    alias3: string
    estado: number,
    fechaRegistro: string,
    fechaModificacion:string
}
export const VariableInit: Variable = {
    id:0,
    idTipoVariable: 0,
    idGrupoVariable: 0,
    descripcion: '',
    descripcionResumida: '',
    tip: '',
    codAtributoTecnicoVariedad: 0,
    idCliente: 0,
    indicadorFotografia: 0,
    numFotos: 0,
    idInputClasificado: 0,
    usaPosible: 0,
    variasRespuestas: 0,
    rangoMinimo: 0,
    rangoMaximo: 0,
    manejoRangos: 0,
    forzarMinimo: 0,
    redondeoMaximo: 0,
    cantidadDecimalesMaximo: 0,
    redondeoMinimo: 0,
    cantidadDecimalesMinimo: 0,
    pesoExtra: 0,
    varEstratificacion: 0,
    tiempoRespuesta: 0,
    usoCalculadora: 0,
    reqUndVta: 0,
    respuestaAfecta: 0,
    funcionResult: 0,
    numeroOrden: 0,
    respuestaObligatoria: 0,
    observaciones: '',
    explicacionFuncionamiento: '',
    alias1: '',
    alias2: '',
    alias3: '',
    estado: 1,
    fechaRegistro: '',
    fechaModificacion:''
};